---
language: python
python:
  - "3.6"
services:
  - docker

env:
  matrix:
    - MOLECULE_SCENARIO: default
    - MOLECULE_SCENARIO: setup_with_collections
    - MOLECULE_SCENARIO: setup_with_collections_copy
    - MOLECULE_SCENARIO: setup_with_external_libs

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - molecule test --scenario-name $MOLECULE_SCENARIO

# after_success:
#   - true
#
# before_deploy:
#   - if [ -n "$TRAVIS_TAG" ]; then git archive HEAD -o $TRAVIS_TAG.tar.gz; fi
#   - if [ -n "$TRAVIS_TAG" ]; then git archive HEAD -o $TRAVIS_TAG.zip; fi
#
# deploy:
#   provider: releases
#   skip_cleanup: true
#   prerelease: true
#   name: $TRAVIS_TAG release
#   file:
#     - $TRAVIS_TAG.tar.gz
#     - $TRAVIS_TAG.zip
#   api_key:
#     secure: AGUiZgxfZVG5c6EvV+n6malKxO3BNDDRfJiHpW+G9zMGnZNTL4Vmmn3tM/rVZ9jvcYHE6nbTvS1GiFftKZ34i/PPgWFeMAUXeX4S8vMXDIpB9V2X9tfTnRxpdMGZtnPL/m2e7ThNXH5djY4W/bAIb/3EcezK5mTDiaLfq0A2DfhYLXoqEprv21Nz1Mq9cP5rpZAMgdv0MYKjovZF3+hyVVkz3hEdDMHgPD/tFszfF3k1T2LVNkvYcq9lEAeJ51BG1hp2vbokd2SBKamyq+S6VvKpN8ysijWVO7CRseXmEbocksDgOi2iBZ/4aalflm/bt/rg0vY75DEwtQ7+ErXkcGU/ojeyRkgWayLdifkcSUqMRsnrmQngGSPEABMV2FThuafdvywZ4WHoqPQls0a2yxJI+nZ38dzCQZ64dTgexGAyCs/goPmmhINloNlFgUI2B6FK42CKXg8xov/PlM/ev20P7Prjk3IuR5PIDWENU2CEXkFYj8A750AXoRVu+BrN37h1xUFA1O92xs2mvjScELxN/t9xGyFKRzLCoufM9sMU4NtZOF5M6sBfioyQvq70Suk96TaZTPTaP5ZuUlkIoDATpsmd4yDa3QiVvlKg+oxvWoG4zyTERAX2H7MtXUisFEEc09wV3ee5/XyCdiK5rZ/OdnHZpXziSE5xHdhXbK4=
#   on:
#     repo: tulibraries/ansible-role-solrcloud
#     tags: true
#     branch:
#       - /^v.*$/

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
