---
language: python
python:
  - "3.6"
services:
  - docker

env:
  matrix:
    - MOLECULE_SCENARIO: default
    - MOLECULE_SCENARIO: setup_with_collections
    - MOLECULE_SCENARIO: setup_with_collections_copy
    - MOLECULE_SCENARIO: setup_with_external_libs

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - molecule test --scenario-name $MOLECULE_SCENARIO

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
