---

- name: SolrCloud | Check if collections configs exists
  uri:
    url: "{{ solr_url }}/{{ item.key }}/config"
    return_content: true
    status_code: 200,404
    force: true
    update: true
  register: config_exists_api_responses
  changed_when: false
  with_dict: "{{ solr_collections }}"

- name: SolrCloud | Clone repo for collections configs in tmp directories
  git:
    repo: "{{ solr_collections_git_repo.url }}"
    version: "{{ solr_collections_git_repo.branch }}"
    dest: "{{ solr_collections_config_tmp_dir }}/{{ solr_collections_git_repo.name }}"
  with_dict: "{{ solr_collections }}"
  register: configs_repo_updated
  notify: Upload SolrCloud Config

- name: SolrCloud | Return existing collections
  uri:
    url: "{{ solr_url }}/admin/collections?action=LIST"
    return_content: true
  register: existing_collections
  changed_when: false

- name: SolrCloud | Create new collections
  uri:
    url: "{{ solr_url }}/admin/collections?action=CREATE&name={{ item }}&numShards={{ solr_collections[item].shards }}&replicationFactor={{ solr_collections[item].replicas }}&collection.configName={{ item }}&maxShardsPerNode={{ solr_collections[item].shards_per_node }}"   # noqa 204
  with_items: "{{ solr_collections.keys() | difference(existing_collections.json.collections) }}"

- name: SolrCloud | Modify existing collections
  uri:
    url: "{{ solr_url }}/admin/collections?action=MODIFYCOLLECTION&collection={{ item }}&replicationFactor={{ solr_collections[item].replicas }}&maxShardsPerNode={{ solr_collections[item].shards_per_node }}&autoAddReplicas=true"   # noqa 204
  with_items: "{{ existing_collections.json.collections | intersect(solr_collections.keys()) }}"

- name: SolrCloud | Reload modified collections
  uri:
    url: "{{ solr_url }}/admin/collections?action=RELOAD&name={{ item }}"
  with_items: "{{ existing_collections.json.collections | intersect(solr_collections.keys()) }}"

- name: SolrCloud | Delete collections that exists in SolrCloud but not in given configuration
  uri:
    url: "{{ solr_url }}/admin/collections?action=DELETE&name={{ item }}"
  with_items: "{{ existing_collections.json.collections | difference(solr_collections.keys()) }}"
