---

- name: SolrCloud | Give execution permission to zkcli script
  ansible.builtin.file:
    path: "{{ solr_zookeeper_client_path }}/zkcli.sh"
    mode: 0744

- name: SolrCloud | Check Root Path (znode) in ZooKeeper
  ansible.builtin.shell: >
    bash {{ solr_zookeeper_client_path }}/zkcli.sh
    -zkhost {{ solr_zookeeper_hosts }}
    -cmd list /{{ solr_zookeeper_hosts_solr_path }}
  register: solr_path_check
  changed_when: false

- name: SolrCloud | Create Root Path (znode) in ZooKeeper using zkcli script
  ansible.builtin.shell: >
    {{ solr_zookeeper_client_path }}/zkcli.sh
    -zkhost {{ solr_zookeeper_hosts }}
    -cmd makepath /{{ solr_zookeeper_hosts_solr_path }}
  when: solr_zookeeper_hosts_solr_path not in solr_path_check.stdout
  register: create_root_path_result
  failed_when: |
    create_root_path_result.rc != 0 and
    "NodeExists" not in create_root_path_result.stderr

- name: SolrCloud | Configuring jetty server
  ansible.builtin.template:
    src: "{{ solr_templates_dir }}/{{ jetty_config_template }}"
    dest: "{{ solr_installation_dir }}/server/etc/jetty.xml"
    force: true
  notify: Restart SolrCloud

- name: SolrCloud | Configuring jetty server http
  ansible.builtin.template:
    src: "{{ solr_templates_dir }}/{{ jetty_http_config_template }}"
    dest: "{{ solr_installation_dir }}/server/etc/jetty-http.xml"
    force: true
  notify: Restart SolrCloud

- name: SolrCloud | Configuring SolrCloud init script
  ansible.builtin.template:
    src: "{{ solr_templates_dir }}/{{ solr_in_sh_template }}"
    dest: /etc/default/solr.in.sh
    force: true
  notify: Restart SolrCloud

- name: SolrCloud | Configuring SolrCloud properties
  ansible.builtin.template:
    src: "{{ solr_templates_dir }}/{{ solr_xml_template }}"
    dest: "{{ solr_data_dir }}/solr.xml"
    force: true
  notify: Restart SolrCloud

- name: SolrCloud | Configuring logging
  ansible.builtin.template:
    src: "{{ solr_templates_dir }}/{{ solr_log_config_file }}.j2"
    dest: "{{ solr_installation_dir }}/{{ solr_log_config_file }}"
    force: true
  notify: Restart SolrCloud

- name: SolrCloud | Install maven_artifact module required packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ solr_external_libraries_required_packages }}"
  notify: Restart SolrCloud
  when: solr_external_libraries is defined and solr_external_libraries|length > 0

- name: SolrCloud | Copy external libraries
  maven_artifact:
    group_id: "{{ item.group_id }}"
    artifact_id: "{{ item.artifact_id }}"
    version: "{{ item.version }}"
    repository_url: "{{ solr_external_libraries_repository_url }}"
    dest: "{{ solr_external_libraries_destination_path }}"
    mode: 0644
  with_items: "{{ solr_external_libraries }}"
  when: solr_external_libraries is defined and solr_external_libraries|length > 0

- name: SolrCloud | Force handlers
  ansible.builtin.meta: flush_handlers

- name: SolrCloud | Wait for SolrCloud to fully startup before continue
  ansible.builtin.uri:
    url: "http://{{ solr_host }}:{{ solr_port }}/solr"
    status_code: 200
  retries: 100
  delay: 1
  register: result
  until: result.status == 200
  changed_when: false

- name: SolrCloud | Check vm.swappiness
  ansible.builtin.command: cat /proc/sys/vm/swappiness
  register: current_swappiness
  changed_when: false

- name: SolrCloud | Set vm.swappiness
  when: (current_swappiness.stdout | int)  != solr_vm_swappiness
  ansible.builtin.command: "sysctl -w vm.swappiness={{ solr_vm_swappiness }}"

- name: SolrCloud | Set vm.swappiness in etc/sysctl
  ansible.builtin.template:
    dest: /etc/sysctl.d/solr.conf
    src: sysctl-solr.conf.j2
