---

- name: SolrCloud | Install
  import_tasks: install.yml
  tags:
    - install

- name: SolrCloud | Configure
  import_tasks: config.yml
  tags:
    - configure

- name: SolrCloud | Service
  import_tasks: service.yml
  tags:
    - service
