---

- name: SolrCloud | Install
  ansible.builtin.import_tasks: install.yml
  tags:
    - install

- name: SolrCloud | Start Service
  ansible.builtin.import_tasks: service.yml
  tags:
    - service

- name: SolrCloud | Reconfigure Service
  ansible.builtin.import_tasks: config.yml
  tags:
    - configure
