---

- name: SolrCloud | Install
  import_tasks: install.yml
  tags:
    - install

- name: SolrCloud | Start Service
  import_tasks: service.yml
  tags:
    - service

- name: SolrCloud | Reconfigure Service
  import_tasks: config.yml
  tags:
    - configure
