---

- name: SolrCloud | Configuring service
  ansible.builtin.service:
    name: solr
    state: "{{ solr_service_state }}"
    enabled: "{{ solr_service_enabled }}"
    sleep: 5
  when: solrcloud_install
