---

- name: Collect Solr service status (Molecule only)
  ansible.builtin.command: systemctl status solr -l --no-pager
  register: solr_status
  changed_when: false
  failed_when: false
  when: molecule_yml is defined

- name: Show Solr service status
  ansible.builtin.debug:
    var: solr_status.stdout_lines
  when: molecule_yml is defined

- name: Collect Solr journal logs (Molecule only)
  ansible.builtin.command: journalctl -xeu solr.service --no-pager --lines=50
  register: solr_journal
  changed_when: false
  failed_when: false
  when: molecule_yml is defined

- name: Show Solr journal logs
  ansible.builtin.debug:
    var: solr_journal.stdout_lines
  when: molecule_yml is defined

- name: SolrCloud | Configuring service
  ansible.builtin.service:
    name: solr
    state: "{{ solr_service_state }}"
    enabled: "{{ solr_service_enabled }}"
    sleep: 5
  when: solrcloud_install
