---
version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2204:current
    working_directory: ~/ansible-role-solrcloud
    environment:
      PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run:
          name: Install
          command: pipenv install --dev
      - run: sudo apt update; sudo apt install rsync
      - run:
          name: Molecule
          command: pipenv run molecule converge
