version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:current
    working_directory: ~/ansible-role-solrcloud
    environment:
      PIPENV_VENV_IN_PROJECT: true
      PYENV_ROOT: ~/.pyenv
      PATH: ~/.pyenv/bin:~/.pyenv/shims:/usr/local/bin:/usr/bin:/bin
    steps:
      - checkout

      - run:
          name: Prevent apt service restart prompts
          command: |
            echo -e '#!/bin/sh\nexit 101' | sudo tee /usr/sbin/policy-rc.d
            sudo chmod +x /usr/sbin/policy-rc.d

      - run:
          name: Install system dependencies (non-interactive)
          command: |
            export DEBIAN_FRONTEND=noninteractive
            sudo apt update
            sudo apt install -y --no-install-recommends \
              make build-essential libssl-dev zlib1g-dev libbz2-dev \
              libreadline-dev libsqlite3-dev wget curl llvm \
              libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev \
              libffi-dev liblzma-dev git python3-pip rsync

      - restore_cache:
          keys:
            - pyenv-3.12.3-v1

      - run:
          name: Install pyenv and Python 3.12.3 if missing
          command: |
            export PYENV_ROOT="$HOME/.pyenv"
            export PATH="$PYENV_ROOT/bin:$PATH"
            if [ ! -d "$PYENV_ROOT" ]; then
              git clone https://github.com/pyenv/pyenv.git ~/.pyenv
            fi
            eval "$(pyenv init --path)"
            if [ ! -d "$PYENV_ROOT/versions/3.12.3" ]; then
              pyenv install 3.12.3
            fi
            pyenv global 3.12.3

      - save_cache:
          key: pyenv-3.12.3-v1
          paths:
            - ~/.pyenv/versions/3.12.3

      - run:
          name: Install pipenv and dependencies
          command: |
            export PYENV_ROOT="$HOME/.pyenv"
            export PATH="$PYENV_ROOT/bin:$PATH"
            eval "$(pyenv init --path)"
            pip install pipenv
            pipenv install --dev

      - run:
          name: Run Molecule tests
          command: |
            export PYENV_ROOT="$HOME/.pyenv"
            export PATH="$PYENV_ROOT/bin:$PATH"
            eval "$(pyenv init --path)"
            pipenv run molecule test
