---
version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2204:current
    working_directory: ~/ansible-role-solrcloud
    environment:
      PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run:
          name: Install Python and Pipenv
          command: |
            sudo apt update
            sudo apt install -y python3 python3-pip rsync
            pip3 install pipenv
      - run: pipenv install --dev
      - run: pipenv run molecule converge
