---
version: 2.1
jobs:
  build:
    working_directory: ~/ansible-role-solrcloud
    docker:
      - image: cimg/python:3.12.3
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run:
          name: Install
          command: pipenv install --dev
      - setup_remote_docker
      - run: sudo apt update; sudo apt install rsync
      - run:
          name: Molecule
          command: pipenv run molecule converge
