---

- name: Restart Zookeeper
  systemd:
    name: zookeeper
    state: restarted
  when: zookeeper_service_state != 'stopped'

- name: Restart SolrCloud
  systemd:
    name: solr
    state: restarted
  when: solr_service_state != 'stopped'
