---
- name: converge
  hosts: zookeeper
  roles:
    - role: geerlingguy.java
    - role: tulibraries.zookeeper
  vars:
    - zookeeper_version: 3.9.4
    - zookeeper_url: https://dlcdn.apache.org/zookeeper/zookeeper-3.9.4/apache-zookeeper-3.9.4-bin.tar.gz


- name: converge
  hosts: solrcloud
  roles:
    - role: geerlingguy.java
    - role: ansible-role-solrcloud
  vars:
    - solr_java_home: /usr/lib/jvm/java-17-openjdk
