---
- name: converge
  hosts: zookeeper
  roles:
    - role: ansible_zookeeper
  vars:
    - zookeeper_version: 3.9.2


- name: converge
  hosts: solrcloud
  roles:
    - role: ansible-role-solrcloud
