---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: zookeeper
    hostname: zookeeper
    image: rockylinux:8
    privileged: true
    cgroupns_mode: host
    command: '/lib/systemd/systemd'
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
    groups:
      - zookeeper-nodes
    networks:
      - name: solr-network
        aliases:
          - zookeeper

  - name: solrcloud1
    hostname: solrcloud1
    image: rockylinux:8
    privileged: true
    cgroupns_mode: host
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
    groups:
      - solrcloud
    command: ''
    networks:
      - name: solr-network
        aliases:
          - solrcloud1
        links:
          - zookeeper:zookeeper
    published_ports:
      - 0.0.0.0:8983:8983/tcp

  - name: solrcloud2
    hostname: solrcloud2
    image: rockylinux:8
    privileged: true
    cgroupns_mode: host
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
    groups:
      - solrcloud
    command: ''
    networks:
      - name: solr-network
        aliases:
          - solrcloud2
        links:
          - zookeeper:zookeeper
    published_ports:
      - 0.0.0.0:8984:8983/tcp
provisioner:
  name: ansible
scenario:
  test_sequence:
    - cleanup
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    # - verify
    - cleanup
    - destroy
verifier:
  name: ansible
