---
- name: Prepare
  hosts: all
  gather_facts: false
  vars:
    ansible_os_family: 'Debian'
  #roles:
    #- role: geerlingguy.git
  tasks:
    - name: Prepare debian for pam settings
      file:
        path: '/etc/default/locale'
        state: touch
