--
- name: converge
  hosts: all
  pre_tasks:
    - name: 'CONFIG | Use Python 3.11 as default selection'
      community.general.alternatives:
        name: python3
        path: /usr/bin/python3.11
        link: /usr/bin/python3
    - name: 'INSTALL | Add python symlink to python3'
      ansible.builtin.file:
        force: true
        dest: "/usr/bin/python"
        src: "/usr/bin/python3"
        state: link
    - name: 'INSTALL | Add pip symlink to pip3'
      ansible.builtin.file:
        force: true
        dest: "/usr/bin/pip"
        src: "/usr/bin/pip3"
        state: link

- name: converge
  hosts: zookeeper
  roles:
    - role: geerlingguy.java
    - role: tulibraries.zookeeper
  vars:
    - zookeeper_version: 3.9.2


- name: converge
  hosts: solrcloud
  roles:
    - role: geerlingguy.java
    - role: ansible-role-solrcloud
