---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: zookeeper
    hostname: zookeeper
    image: bitnami/zookeeper:3.9.2-debian-12-r7
    privileged: true
    cgroupns_mode: host
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
    groups:
      - zookeeper_group
    command: '/lib/systemd/systemd'
    networks:
      - name: solr-network
        aliases:
          - zookeeper

  - name: solrcloud1
    hostname: solrcloud1
    image: bitnami/solr:8.11.3-debian-12-r9
    privileged: true
    cgroupns_mode: host
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
    groups:
      - solrcloud
    command: '/lib/systemd/systemd'
    networks:
      - name: solr-network
        aliases:
          - solrcloud1
        links:
          - zookeeper:zookeeper
    published_ports:
      - 0.0.0.0:8983:8983/tcp

  - name: solrcloud2
    hostname: solrcloud2
    image: bitnami/solr:8.11.3-debian-12-r9
    privileged: true
    cgroupns_mode: host
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
    groups:
      - solrcloud
    command: '/lib/systemd/systemd'
    networks:
      - name: solr-network
        aliases:
          - solrcloud2
        links:
          - zookeeper:zookeeper
    published_ports:
      - 0.0.0.0:8984:8983/tcp
provisioner:
  name: ansible
scenario:
  test_sequence:
    - cleanup
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  name: ansible
